// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: pkg/proto/transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordWithdrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency   string `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Chain      string `protobuf:"bytes,2,opt,name=Chain,proto3" json:"Chain,omitempty"`
	Amount     string `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Address    string `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	ExecutedAt string `protobuf:"bytes,5,opt,name=ExecutedAt,proto3" json:"ExecutedAt,omitempty"`
}

func (x *RecordWithdrawRequest) Reset() {
	*x = RecordWithdrawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transaction_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWithdrawRequest) ProtoMessage() {}

func (x *RecordWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWithdrawRequest.ProtoReflect.Descriptor instead.
func (*RecordWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *RecordWithdrawRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RecordWithdrawRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *RecordWithdrawRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RecordWithdrawRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RecordWithdrawRequest) GetExecutedAt() string {
	if x != nil {
		return x.ExecutedAt
	}
	return ""
}

type RecordWithdrawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordWithdrawResponse) Reset() {
	*x = RecordWithdrawResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_transaction_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWithdrawResponse) ProtoMessage() {}

func (x *RecordWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_transaction_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWithdrawResponse.ProtoReflect.Descriptor instead.
func (*RecordWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

var File_pkg_proto_transaction_transaction_proto protoreflect.FileDescriptor

var file_pkg_proto_transaction_transaction_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x15, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x73, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x61, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x12, 0x26, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x6d, 0x67, 0x6d, 0x74,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x75, 0x72, 0x74, 0x69, 0x6c, 0x65, 0x6b, 0x61, 0x73,
	0x73, 0x61, 0x6e, 0x6b, 0x68, 0x61, 0x6e, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x75, 0x70, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_proto_transaction_transaction_proto_rawDescOnce sync.Once
	file_pkg_proto_transaction_transaction_proto_rawDescData = file_pkg_proto_transaction_transaction_proto_rawDesc
)

func file_pkg_proto_transaction_transaction_proto_rawDescGZIP() []byte {
	file_pkg_proto_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_pkg_proto_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_transaction_transaction_proto_rawDescData)
	})
	return file_pkg_proto_transaction_transaction_proto_rawDescData
}

var file_pkg_proto_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_transaction_transaction_proto_goTypes = []interface{}{
	(*RecordWithdrawRequest)(nil),  // 0: transactionmgmt.RecordWithdrawRequest
	(*RecordWithdrawResponse)(nil), // 1: transactionmgmt.RecordWithdrawResponse
}
var file_pkg_proto_transaction_transaction_proto_depIdxs = []int32{
	0, // 0: transactionmgmt.UserManagement.RecordWithdraw:input_type -> transactionmgmt.RecordWithdrawRequest
	1, // 1: transactionmgmt.UserManagement.RecordWithdraw:output_type -> transactionmgmt.RecordWithdrawResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_transaction_transaction_proto_init() }
func file_pkg_proto_transaction_transaction_proto_init() {
	if File_pkg_proto_transaction_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_transaction_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordWithdrawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_transaction_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordWithdrawResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_transaction_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_pkg_proto_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_pkg_proto_transaction_transaction_proto_msgTypes,
	}.Build()
	File_pkg_proto_transaction_transaction_proto = out.File
	file_pkg_proto_transaction_transaction_proto_rawDesc = nil
	file_pkg_proto_transaction_transaction_proto_goTypes = nil
	file_pkg_proto_transaction_transaction_proto_depIdxs = nil
}
